### ISSUE TITLE
Trigger an action on tap and on dismissed

### ISSUE THREAD

**Issue by fictionteamapps** [Nolence/just_the_tooltip#41]

**Comment by stargazing-dino** [comment]
Hi ! Yeah, you can do that with a controller now.

Here's some code:

```dart
@override
void initState() {
  // Programatically display tooltip after two seconds
  Future.delayed(const Duration(seconds: 2), () {
    tooltipController.showTooltip(immediately: false);
  });

  tooltipController.addListener(() {
    // Prints the enum value of [TooltipStatus.isShowing] or [TooltipStatus.isHiding]
    if (tooltipController.value == TooltipStatus.isShowing) {
      // my logic
    }
  });
}
```

You'll just need to create a controller as you would any other and pass it through the JustTheTooltip constructor.

-----

If you mean it'd be cool to have callbacks on the actual constructor:

```dart
JustTheTooltip(
  onClose: () {},
  onOpen: () {}
)
```

that's another thing and I'd gladly look at a PR

### Edit

Make sure you're on version 0.0.10. That's the latest one with better controller state handling

**Comment by fictionteamapps** [comment]
JustTheTooltip(
  onClose: () {},
  onOpen: () {}
)

Yeah, that's what I meant 
I hope to be added soon, Thank you

**Comment by stargazing-dino** [comment]
Thank you the suggestion. 0.0.11 now has these callbacks. For any issues with them, please raise a new issue. Thank you !

```dart
JustTheTooltip(
  onDismiss: () {
    // do something
  },
  onShow: () {
    // something else
  }
),
```
