### ISSUE TITLE
 Error: Type 'TooltipTriggerMode' not found.   final TooltipTriggerMode? triggerMode

### ISSUE THREAD

**Issue by abhipoojary** [Nolence/just_the_tooltip#42]
app is working in debug mode, but its throwing several errors when i try to build the APK. Bellow i will mention the errors which i got.

`../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:80:9: Error: Type 'TooltipTriggerMode' not found.
  final TooltipTriggerMode? triggerMode;                                
        ^^^^^^^^^^^^^^^^^^                                              
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:288:16: Error: Type 'TooltipTriggerMode' not found.
  static const TooltipTriggerMode _defaultTriggerMode =                 
               ^^^^^^^^^^^^^^^^^^                                       
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:300:8: Error: Type 'TooltipTriggerMode' not found.
  late TooltipTriggerMode triggerMode;                                  
       ^^^^^^^^^^^^^^^^^^                                               
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip_entry.dart:60:9: Error: Type 'TooltipTriggerMode' not found.
  final TooltipTriggerMode? triggerMode;                                
        ^^^^^^^^^^^^^^^^^^                                              
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/models/just_the_interface.dart:125:3: Error: Type 'TooltipTriggerMode' not found.
  TooltipTriggerMode? get triggerMode;                                  
  ^^^^^^^^^^^^^^^^^^                                                    
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:289:7: Error: Getter not found: 'TooltipTriggerMode'.
      TooltipTriggerMode.longPress;                                     
      ^^^^^^^^^^^^^^^^^^                                                
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:80:9: Error: 'TooltipTriggerMode' isn't a type.
  final TooltipTriggerMode? triggerMode;                                
        ^^^^^^^^^^^^^^^^^^                                              
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:288:16: Error: 'TooltipTriggerMode' isn't a type.
  static const TooltipTriggerMode _defaultTriggerMode =                 
               ^^^^^^^^^^^^^^^^^^                                       
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:300:8: Error: 'TooltipTriggerMode' isn't a type.
  late TooltipTriggerMode triggerMode;                                  
       ^^^^^^^^^^^^^^^^^^                                               
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:559:26: Error: The getter 'TooltipTriggerMode' isn't defined for the class '_JustTheTooltipState<T>'.
 - '_JustTheTooltipState' is from 'package:just_the_tooltip/src/just_the_tooltip.dart' ('../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TooltipTriggerMode'.
      if (triggerMode == TooltipTriggerMode.longPress) {                
                         ^^^^^^^^^^^^^^^^^^                             
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:581:44: Error: The getter 'triggerMode' isn't defined for the class 'TooltipThemeData'.
 - 'TooltipThemeData' is from 'package:flutter/src/material/tooltip_theme.dart' ('../../src/flutter_2.2.3/packages/flutter/lib/src/material/tooltip_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'triggerMode'.
        widget.triggerMode ?? tooltipTheme.triggerMode ?? _defaultTriggerMode;
                                           ^^^^^^^^^^^                  
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:583:22: Error: The getter 'enableFeedback' isn't defined for the class 'TooltipThemeData'.
 - 'TooltipThemeData' is from 'package:flutter/src/material/tooltip_theme.dart' ('../../src/flutter_2.2.3/packages/flutter/lib/src/material/tooltip_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enableFeedback'.
        tooltipTheme.enableFeedback ??                                  
                     ^^^^^^^^^^^^^^                                     
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:590:29: Error: The getter 'TooltipTriggerMode' isn't defined for the class '_JustTheTooltipState<T>'.
 - '_JustTheTooltipState' is from 'package:just_the_tooltip/src/just_the_tooltip.dart' ('../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TooltipTriggerMode'.
          : (triggerMode == TooltipTriggerMode.longPress)               
                            ^^^^^^^^^^^^^^^^^^                          
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart:595:29: Error: The getter 'TooltipTriggerMode' isn't defined for the class '_JustTheTooltipState<T>'.
 - '_JustTheTooltipState' is from 'package:just_the_tooltip/src/just_the_tooltip.dart' ('../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TooltipTriggerMode'.
          : (triggerMode == TooltipTriggerMode.tap)                     
                            ^^^^^^^^^^^^^^^^^^                          
../../src/flutter_2.2.3/.pub-cache/hosted/pub.dartlang.org/just_the_tooltip-0.0.10/lib/src/just_the_tooltip_entry.dart:60:9: Error: 'TooltipTriggerMode' isn't a type.
  final TooltipTriggerMode? triggerMode;                                
        ^^^^^^^^^^^^^^^^^^                                              
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/mindstack/src/flutter_2.2.3/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/mindstack/src/flutter_2.2.3/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
`

**Comment by stargazing-dino** [comment]
Sorry for late response. I think around Flutter `2.3` (?) introduced [`TooltipTriggerMode`](https://github.com/flutter/flutter/pull/84434) to keep track of how a tooltip is shown. This package just follows the standard tooltip implementation with small added stuff on top so it looks like just a version mismatch somewhere. Perhaps you are building prod for a different version somehow? Really not sure

I currently test against the [dev and stable](https://github.com/Nolence/just_the_tooltip/actions) branch of Flutter where all tests are currently passing but let me know if there's something I'm missing

**Comment by Vidtion** [comment]
same on flutter 2.2.3

**Comment by Bes79** [comment]
save issue on flutter 2.8.1

**Comment by stargazing-dino** [comment]
Sorry guys, I'm closing this. I test against against stable and beta and they both support TooltipTriggerMode. Your issue is very likely related to just using an older version of flutter than the two I test against. Feel free to reopen another issue with further details and we can have another look
