### ISSUE TITLE
onShow, onHide callbacks

### ISSUE THREAD

**Issue by Hassanch15** [Nolence/just_the_tooltip#43]
I am using a widget by tapping it i am showing a tooltip. but i also want to change the size, colour of the tooltip but unable to do because i am not getting any callback of show and close in which i can change the widget.It would be great if those call backs are added soon. Thank you.

**Comment by stargazing-dino** [comment]
Thanks for the suggestion. 0.0.11 now has these callbacks. For any issues with them, please raise a new issue. Thank you !

```dart
JustTheTooltip(
  onDismiss: () {
    // Maybe continue tutorial?
  },
  onShow: () {
    // Start animation?
  }
),
```
