### ISSUE TITLE
Gesture Detector in other page wont work if the page is redirected from tooltip

### ISSUE THREAD

**Issue by encoteki** [Nolence/just_the_tooltip#65]
I tried to display some content inside my tooltip and there's also a button in my tooltip that redirect my app to another screen. If I access that screen from my tooltip all of the gesture detector in that page won't work and got disabled

Is there any work around for this Issue ?

**Comment by NicolasLaube** [comment]
I'm curious to know how you achieved to solve this pb @developerencoteki !
Thanks in advance for your response
